POST http://localhost:3000/api/v1/auth/register HTTP/1.1
content-type: application/json

{
  "name": "テストユーザー2",
  "username": "testuser2",
  "birthdate": "{{$datetime iso8601}}",
  "email": "20c1010019rh@edu.tech.ac.jp",
  "password": "password",
  "schoolCode": "techc"
}

###

POST http://localhost:3000/api/v1/auth/login HTTP/1.1
content-type: application/json

{
  "email": "20c1010019rh@edu.tech.ac.jp",
  "password": "password"
}

###

POST http://localhost:3000/api/v1/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJja2o4cDl4a2cwMDAwN2QxYXo1cm0zaDlvIiwiaWF0IjoxNjA5MTY4MzUxfQ.5ZQMWAKDcDch_vLyfu0KfyKbwSl6ha38EJDkKV7xQCE

###