@baseUrl=http://localhost:3000/api/v1/auth

POST {{baseUrl}}/register HTTP/1.1
content-type: application/json

{
  "name": "テストユーザー2",
  "username": "testuser2",
  "birthdate": "{{$datetime iso8601}}",
  "email": "20c1010019rh@edu.tech.ac.jp",
  "password": "password",
  "schoolCode": "techc"
}

###

# @name login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
  "email": "20c1010019rh@edu.tech.ac.jp",
  "password": "password"
}

###

@authToken = {{login.response.body.authToken}}

POST {{baseUrl}}/logout HTTP/1.1
Authorization: Bearer {{authToken}}

###