@baseUrl=http://localhost:3000/api/v1/user

# @name login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
  "email": "20c1010019rh@edu.tech.ac.jp",
  "password": "password"
}

###

@authToken = {{login.response.body.authToken}}

GET {{baseUrl}}/me HTTP/1.1
Authorization: Bearer {{authToken}}

###

POST {{baseUrl}}/card HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "studentNumber": "20c1010019",
  "department": "スーパーITエンジニア"
}

###

GET {{baseUrl}}/card HTTP/1.1
Authorization: Bearer {{authToken}}